// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFCjnfVVNqZB99KXnb5d6IGXS0drhGciQ',
    appId: '1:1026717261015:web:4d4c3bb4afb9f61ee4a492',
    messagingSenderId: '1026717261015',
    projectId: 'dashboard-cd096',
    authDomain: 'dashboard-cd096.firebaseapp.com',
    storageBucket: 'dashboard-cd096.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpzgcclpUop8P1clnUaLGFjZN4d3aKQNQ',
    appId: '1:1026717261015:android:931985f7a068137be4a492',
    messagingSenderId: '1026717261015',
    projectId: 'dashboard-cd096',
    storageBucket: 'dashboard-cd096.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3CDcTuFWNk9gwUxVlptk4loC4X5tDr90',
    appId: '1:1026717261015:ios:205ee63f6bf5376ee4a492',
    messagingSenderId: '1026717261015',
    projectId: 'dashboard-cd096',
    storageBucket: 'dashboard-cd096.appspot.com',
    iosBundleId: 'com.example.dashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3CDcTuFWNk9gwUxVlptk4loC4X5tDr90',
    appId: '1:1026717261015:ios:205ee63f6bf5376ee4a492',
    messagingSenderId: '1026717261015',
    projectId: 'dashboard-cd096',
    storageBucket: 'dashboard-cd096.appspot.com',
    iosBundleId: 'com.example.dashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFCjnfVVNqZB99KXnb5d6IGXS0drhGciQ',
    appId: '1:1026717261015:web:eeb1e195a8794d4be4a492',
    messagingSenderId: '1026717261015',
    projectId: 'dashboard-cd096',
    authDomain: 'dashboard-cd096.firebaseapp.com',
    storageBucket: 'dashboard-cd096.appspot.com',
  );

}